### ISSUE TITLE
Latest 1.20.4 Neoforge builds built with class file version 65.0

### ISSUE THREAD

**Issue by cuiviemen** [Hexeption/RSInfinityBooster#35]
As title says latest (rsinfinitybooster-neoforge-1.20.4-1.0.0.34.jar) are built targetting JAVA 21 (class file version 65.0). Since minectraft is bundled with either JDK 17 or JRE8 then the mod/jar does not load using builtin JDK17/JRE8 (or any other JDK/JRE lesser than 21).

Same goes for aeinfinitybooster-neoforge-1.20.4-1.0.1.33.jar.

```
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
-- MOD rsinfinitybooster --
Details:
	Mod File: .minecraft/1.20.4/mods/rsinfinitybooster-neoforge-1.20.4-1.0.0.34.jar
	Failure message: RSInfinityBooster has class loading errors
		java.lang.UnsupportedClassVersionError: uk/co/hexeption/rsinfinitybooster/RSInfinityBooster has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	Mod Version: 1.20.4-1.0.0.34
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.UnsupportedClassVersionError: uk/co/hexeption/rsinfinitybooster/RSInfinityBooster has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:175) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288) ~[securejarhandler-2.1.24.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?] {}
	at java.lang.Class.forName(Class.java:545) ~[?:?] {re:mixin}
	at net.neoforged.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:57) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at net.neoforged.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:46) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at net.neoforged.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:299) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at net.neoforged.fml.ModLoader.lambda$buildMods$24(ModLoader.java:266) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?] {}
	at net.neoforged.fml.ModLoader.buildMods(ModLoader.java:268) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[?:?] {}
	at net.neoforged.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[loader-2.0.17.jar%2396!/:2.0] {}
	at net.neoforged.neoforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:56) ~[neoforge-20.4.234-universal.jar%23418!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.neoforged.neoforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:75) ~[neoforge-20.4.234-universal.jar%23418!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.neoforged.neoforge.client.loading.ClientModLoader.begin(ClientModLoader.java:56) ~[neoforge-20.4.234-universal.jar%23418!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:494) ~[client-1.20.4-20231207.154220-srg.jar%23417!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.hammerlib.json:client.MinecraftMixin from mod hammerlib,pl:mixin:APP:mffs.mixins.json:MinecraftMixin from mod mffs,pl:mixin:APP:balm.neoforge.mixins.json:MinecraftMixin from mod balm,pl:mixin:APP:resourcefulconfig.mixins.json:client.MinecraftMixin from mod resourcefulconfig,pl:mixin:APP:architectury.mixins.json:MixinMinecraft from mod architectury,pl:mixin:APP:emi.mixins.json:MinecraftClientMixin from mod emi,pl:mixin:APP:ae2.mixins.json:PickColorMixin from mod ae2,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess from mod immersiveengineering,pl:mixin:APP:chunkpregen.mixins.json:client.MinecraftMixin from mod (unknown),pl:mixin:APP:glitchcore.mixins.json:client.MixinMinecraft from mod (unknown),pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[neoforge-20.4.234.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-2.0.17.jar:2.0] {}
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-2.0.17.jar:2.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```

**Comment by Hexeption** [comment]
fixed

**Comment by cuiviemen** [comment]
[This](https://github.com/Hexeption/RSInfinityBooster/commit/2fbca46ad451db80fd387e3e07fcd305827ede99) won't help  because `build.gradle` still [targets java 21](https://github.com/Hexeption/RSInfinityBooster/blob/2fbca46ad451db80fd387e3e07fcd305827ede99/build.gradle#L59)
